/**
    Form for choose texture in Nuke3D Editor
    Copyright (C) 2019 Anton "Vuvk" Shcherbatykh <vuvk69@gmail.com>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/
package com.vuvk.n3d.editor.forms;

import com.vuvk.n3d.resources.Texture;
import com.vuvk.n3d.utils.ImageUtils;
import java.awt.Component;
import java.awt.event.MouseEvent;
import java.awt.event.WindowEvent;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Anton "Vuvk" Shcherbatykh
 */
public class FormTextureSelector extends javax.swing.JDialog {
    
    /** доступен ли выбор текстуры или это просто просмотр */
    public boolean isApplyButtonVisible = true;
    /** выбранная текстура */
    public Texture selectedTexture = null;
    
    /**
     * кастомный рендерер для ячеек списка
     */
    class TextureCellRenderer extends JLabel implements ListCellRenderer {
        public TextureCellRenderer() {        
            setOpaque(true);
            setHorizontalAlignment(CENTER);
            setVerticalAlignment(CENTER);
            setHorizontalTextPosition(CENTER);
            setVerticalTextPosition(BOTTOM);
        }
        
        @Override
        public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {        
            if (isSelected) {
                setBackground(list.getSelectionBackground());
                setForeground(list.getSelectionForeground());
            } else {
                setBackground(list.getBackground());
                setForeground(list.getForeground());
            }         
            
            Texture txr = (Texture) value;
            ImageIcon icon = new ImageIcon();
            
            double imageWidth = txr.getImage().getWidth();
            double imageHeight = txr.getImage().getHeight();
            
            int iconWidth  = 96;
            int iconHeight = 96;
            
            if (imageWidth != imageHeight) {
                if (imageWidth > imageHeight) {
                    iconHeight = (int)((double)iconHeight * (imageHeight / imageWidth));
                } else {
                    iconWidth = (int)((double)iconWidth * (imageWidth / imageHeight));
                }
            }
            
            icon.setImage(ImageUtils.resizeImage(txr.getImage(), iconWidth, iconHeight));
            
            setIcon(icon);            
            setText(txr.getName());
   

            return this;
        }        
    }
    
    /**
     * Creates new form FormTextureSelector
     */
    public FormTextureSelector(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        setLocationRelativeTo(null);
        
        DefaultListModel listModel = new DefaultListModel();
        //model.setSize(Texture.list.size());
        for (Texture txr : Texture.TEXTURES) {
            listModel.addElement(txr);
        }
        ListTextures.setModel(listModel);       
        
        // задаем кастомный рендерер
        ListTextures.setCellRenderer(new TextureCellRenderer());
        
        // кастомное событие выбора ячейки        
        ListSelectionModel selModel = ListTextures.getSelectionModel();
        selModel.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                int index = ListTextures.getSelectedIndex();
                if (index > -1 && index < Texture.TEXTURES.size()) {
                    selectedTexture = Texture.TEXTURES.get(index);
                } else {
                    selectedTexture = null;
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonClose = new javax.swing.JButton();
        ButtonApply = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListTextures = new javax.swing.JList<>();

        setTitle("Просмотр текстур");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        ButtonClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vuvk/n3d/ico/cancel_small.png"))); // NOI18N
        ButtonClose.setText("Отменить");
        ButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCloseActionPerformed(evt);
            }
        });

        ButtonApply.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vuvk/n3d/ico/apply.png"))); // NOI18N
        ButtonApply.setText("Принять");
        ButtonApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonApplyActionPerformed(evt);
            }
        });

        ListTextures.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 6", "Item 7", "Item 8", "Item 9", "Item 10", "Item 11", "Item 12", "Item 13", "Item 14", "Item 15", "Item 16", "Item 17", "Item 18", "Item 19", "Item 20", "Item 21", "Item 22", "Item 23", "Item 24", "Item 25", "Item 26", "Item 27", "Item 28", "Item 29" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListTextures.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        ListTextures.setAutoscrolls(false);
        ListTextures.setDoubleBuffered(true);
        ListTextures.setFixedCellHeight(128);
        ListTextures.setFixedCellWidth(128);
        ListTextures.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        ListTextures.setVisibleRowCount(-1);
        ListTextures.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListTexturesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListTextures);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ButtonApply, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonClose)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonApply)
                    .addComponent(ButtonClose))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        ButtonApply.setVisible(isApplyButtonVisible);
    }//GEN-LAST:event_formWindowActivated

    private void ButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCloseActionPerformed
        selectedTexture = null;
        dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_ButtonCloseActionPerformed

    private void ButtonApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonApplyActionPerformed
        dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_ButtonApplyActionPerformed

    private void ListTexturesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListTexturesMouseClicked
        // если режим выбора текстуры, то на двойной клик закрыть окно
        if (evt.getButton() == MouseEvent.BUTTON1 && evt.getClickCount() == 2) {
            if (ListTextures.getSelectedIndex() != -1) {
                if (isApplyButtonVisible) {
                    dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
                }
            }
        }
    }//GEN-LAST:event_ListTexturesMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonApply;
    private javax.swing.JButton ButtonClose;
    private javax.swing.JList<String> ListTextures;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
