/**
    Dialog for choose and open sound/music file (Nuke3D Editor)
    Copyright (C) 2019 Anton "Vuvk" Shcherbatykh <vuvk69@gmail.com>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/
package com.vuvk.n3d.forms;

import com.vuvk.n3d.components.ImageFileView;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.commons.io.FileUtils;

/**
 *
 * @author Anton "Vuvk" Shcherbatykh
 */
public class DialogOpenSound extends javax.swing.JDialog {    
    /** выбранный файл */
    public static File selectedFile = null;
    /** путь до ресурсов */
    public static File currentPath = FileUtils.getUserDirectory();
    
    
    /**
     * Creates new form DialogOpenTexture
     */
    public DialogOpenSound(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        FileNameExtensionFilter filterAll  = new FileNameExtensionFilter("All knowns formats", "wav", "ogg", "mp3");
        FileNameExtensionFilter filterWav = new FileNameExtensionFilter("Waveform Audio File (WAV)", "wav");
        FileNameExtensionFilter filterOgg  = new FileNameExtensionFilter("Ogg Vorbis (OGG)", "ogg");
        FileNameExtensionFilter filterMP3  = new FileNameExtensionFilter("MPEG-1/2/2.5 Layer 3 (MP3)", "mp3");
        FileChooser.setAcceptAllFileFilterUsed(false);
        FileChooser.setFileFilter(filterAll);
        FileChooser.addChoosableFileFilter(filterWav);
        FileChooser.addChoosableFileFilter(filterOgg);
        FileChooser.addChoosableFileFilter(filterMP3);  
        FileChooser.setFileView(new ImageFileView());
                
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FileChooser = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select texture for import");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        FileChooser.setCurrentDirectory(null);
        FileChooser.setDialogTitle("");
        FileChooser.setFileFilter(null);
        FileChooser.setAutoscrolls(true);
        FileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileChooserActionPerformed(evt);
            }
        });
        FileChooser.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                FileChooserPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FileChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FileChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileChooserActionPerformed
        switch (evt.getActionCommand()) {
            // нажато "Открыть"
            case JFileChooser.APPROVE_SELECTION :
                selectedFile = FileChooser.getSelectedFile();        
                currentPath = FileChooser.getCurrentDirectory();
                break;
                
            // нажато "отмена
            case JFileChooser.CANCEL_SELECTION : 
                selectedFile = null;
                break;
        }
        
        dispose();
    }//GEN-LAST:event_FileChooserActionPerformed

    private void FileChooserPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_FileChooserPropertyChange
        
    }//GEN-LAST:event_FileChooserPropertyChange

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        selectedFile = null;
        FileChooser.setCurrentDirectory(currentPath);
    }//GEN-LAST:event_formWindowOpened

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser FileChooser;
    // End of variables declaration//GEN-END:variables
}
